export type { OperatorSignalId, OperatorSignalPayload } from "./operator-signal-types";

export type {
  AnonymousOpportunitiesBlockData,
  AnonymousOpportunity,
  ConsultationRequestQueueBlockData,
  ConsultationRequestQueueItem,
  ConversationWorkspaceBlockData,
  CustomerWorkflowContinuityBlockData,
  CustomerWorkflowContinuityItem,
  DealQueueBlockData,
  DealQueueItem,
  FunnelRecommendationsBlockData,
  FunnelRecommendation,
  LeadQueueBlockData,
  LeadQueueLead,
  RecentConversationLink,
  RecentConversationsBlockData,
  RecurringPainTheme,
  RecurringPainThemesBlockData,
  RoutingReviewConversation,
  RoutingReviewBlockData,
  RoutingReviewRecentChange,
  RoutingReviewSummary,
  SystemHealthBlockData,
  TrainingPathQueueBlockData,
  TrainingPathQueueItem,
  AnonymousOpportunitiesBlockData as OperatorAnonymousOpportunitiesData,
  AnonymousOpportunity as OperatorAnonymousOpportunity,
  ConsultationRequestQueueBlockData as OperatorConsultationRequestQueueData,
  ConsultationRequestQueueItem as OperatorConsultationRequestEntry,
  ConversationWorkspaceBlockData as OperatorConversationWorkspaceData,
  CustomerWorkflowContinuityBlockData as OperatorCustomerWorkflowContinuityData,
  CustomerWorkflowContinuityItem as OperatorCustomerWorkflowItem,
  DealQueueBlockData as OperatorDealQueueData,
  DealQueueItem as OperatorDealQueueEntry,
  FunnelRecommendationsBlockData as OperatorFunnelRecommendationsData,
  FunnelRecommendation as OperatorFunnelRecommendation,
  LeadQueueBlockData as OperatorLeadQueueData,
  LeadQueueLead as OperatorLeadQueueEntry,
  RecentConversationLink as OperatorRecentConversationLink,
  RecentConversationsBlockData as OperatorRecentConversationsData,
  RecurringPainTheme as OperatorRecurringPainTheme,
  RecurringPainThemesBlockData as OperatorRecurringPainThemesData,
  RoutingReviewBlockData as OperatorRoutingReviewData,
  RoutingReviewConversation as OperatorRoutingRiskConversation,
  RoutingReviewRecentChange as OperatorRoutingRecentChange,
  RoutingReviewSummary as OperatorRoutingSummary,
  SystemHealthBlockData as OperatorSystemHealthData,
  TrainingPathQueueBlockData as OperatorTrainingPathQueueData,
  TrainingPathQueueItem as OperatorTrainingPathQueueEntry,
} from "./operator-signal-backend";

export {
  loadAnonymousOpportunitiesBlock,
  loadConsultationRequestQueueBlock,
  loadConversationWorkspaceBlock,
  loadCustomerWorkflowContinuityBlock,
  loadDealQueueBlock,
  loadFunnelRecommendationsBlock,
  loadLeadQueueBlock,
  loadRecentConversationsBlock,
  loadRecurringPainThemesBlock,
  loadRoutingReviewBlock,
  loadSystemHealthBlock,
  loadTrainingPathQueueBlock,
} from "./operator-signal-backend";

export {
  loadAnonymousOpportunitiesBlock as loadOperatorAnonymousOpportunities,
  loadConsultationRequestQueueBlock as loadOperatorConsultationRequests,
  loadConversationWorkspaceBlock as loadOperatorConversationWorkspace,
  loadCustomerWorkflowContinuityBlock as loadOperatorCustomerWorkflowContinuity,
  loadDealQueueBlock as loadOperatorDealQueue,
  loadFunnelRecommendationsBlock as loadOperatorFunnelRecommendations,
  loadLeadQueueBlock as loadOperatorLeadQueue,
  loadRecentConversationsBlock as loadOperatorRecentConversations,
  loadRecurringPainThemesBlock as loadOperatorRecurringPainThemes,
  loadRoutingReviewBlock as loadOperatorRoutingReview,
  loadSystemHealthBlock as loadOperatorSystemHealth,
  loadTrainingPathQueueBlock as loadOperatorTrainingPathQueue,
} from "./operator-signal-backend";