export default {
  extends: ["stylelint-config-standard"],
  ignoreFiles: [
    ".next/**",
    "coverage/**",
    "node_modules/**",
    "test-results/**",
  ],
  rules: {
    "alpha-value-notation": null,
    "at-rule-no-unknown": [true, {
      ignoreAtRules: [
        "apply",
        "custom-variant",
        "layer",
        "theme",
        "utility",
      ],
    }],
    "comment-empty-line-before": null,
    "custom-property-empty-line-before": null,
    "color-function-alias-notation": null,
    "color-function-notation": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-block-single-line-max-declarations": null,
    "declaration-empty-line-before": null,
    "hue-degree-notation": null,
    "import-notation": null,
    "lightness-notation": null,
    "media-feature-range-notation": null,
    "nesting-selector-no-missing-scoping-root": null,
    "no-empty-source": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "number-max-precision": null,
    "property-no-vendor-prefix": null,
    "rule-empty-line-before": null,
    "value-keyword-case": null,
  },
};