export const REASON_CODES = {
  // Chat stream
  ROUTING_ANALYSIS_FAILED: "ROUTING_ANALYSIS_FAILED",
  ATTACHMENT_ASSIGN_FAILED: "ATTACHMENT_ASSIGN_FAILED",
  CONVERSATION_LOOKUP_FAILED: "CONVERSATION_LOOKUP_FAILED",
  MESSAGE_PERSIST_FAILED: "MESSAGE_PERSIST_FAILED",

  // Orchestrator
  TOOL_EXECUTION_FAILED: "TOOL_EXECUTION_FAILED",
  TOOL_ROUND_LIMIT_EXCEEDED: "TOOL_ROUND_LIMIT_EXCEEDED",

  // Embedder
  EMBEDDER_PIPELINE_LOAD_FAILED: "EMBEDDER_PIPELINE_LOAD_FAILED",
  EMBEDDING_FAILED: "EMBEDDING_FAILED",

  // TTS
  TTS_CACHE_READ_FAILED: "TTS_CACHE_READ_FAILED",
  TTS_PROVIDER_FAILED: "TTS_PROVIDER_FAILED",
  TTS_TIMEOUT: "TTS_TIMEOUT",

  // General
  UNKNOWN_ROUTE_ERROR: "UNKNOWN_ROUTE_ERROR",
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
