import Database from "better-sqlite3";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { BlogAssetDataMapper } from "@/adapters/BlogAssetDataMapper";
import { BlogPostDataMapper } from "@/adapters/BlogPostDataMapper";
import { BlogImageGenerationService } from "@/lib/blog/blog-image-generation-service";
import { ensureSchema } from "@/lib/db/schema";

describe("BlogImageGenerationService", () => {
  let db: Database.Database;
  let tempDir: string;

  beforeEach(() => {
    db = new Database(":memory:");
    db.pragma("foreign_keys = ON");
    ensureSchema(db);
    db.prepare(`INSERT OR IGNORE INTO users (id, email, name) VALUES (?, ?, ?)`)
      .run("usr_admin", "admin@example.com", "Admin");
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "studio-ordo-blog-image-service-"));
    process.env.STUDIO_ORDO_BLOG_ASSET_ROOT = tempDir;
  });

  afterEach(() => {
    delete process.env.STUDIO_ORDO_BLOG_ASSET_ROOT;
    fs.rmSync(tempDir, { recursive: true, force: true });
    db.close();
  });

  it("stores generated bytes, creates a blog asset, and links it as the hero image", async () => {
    const blogRepo = new BlogPostDataMapper(db);
    const assetRepo = new BlogAssetDataMapper(db);
    const post = await blogRepo.create({
      slug: "image-service-post",
      title: "Image Service Post",
      description: "Testing image generation service.",
      content: "## Hero\n\nBody.",
      createdByUserId: "usr_admin",
    });
    const provider = {
      generate: vi.fn().mockResolvedValue({
        bytes: Buffer.from("image-binary"),
        mimeType: "image/png",
        width: 1536,
        height: 1024,
        originalPrompt: "Original prompt",
        finalPrompt: "Final prompt",
        provider: "openai",
        model: "gpt-image-1",
      }),
    };
    const service = new BlogImageGenerationService(blogRepo, assetRepo, provider);

    const result = await service.generate({
      postId: post.id,
      prompt: "Original prompt",
      altText: "A generated hero image.",
      size: "1536x1024",
      quality: "high",
      enhancePrompt: true,
      createdByUserId: "usr_admin",
    });

    const linkedPost = await blogRepo.findById(post.id);
    const asset = result.assetId ? await assetRepo.findById(result.assetId) : null;

    expect(provider.generate).toHaveBeenCalledOnce();
    expect(result).toMatchObject({
      postId: post.id,
      postSlug: post.slug,
      heroImageAssetId: result.assetId,
      visibility: "draft",
      imageUrl: `/api/blog/assets/${result.assetId}`,
    });
    expect(linkedPost?.heroImageAssetId).toBe(result.assetId);
    expect(asset).toMatchObject({
      id: result.assetId,
      postId: post.id,
      altText: "A generated hero image.",
      visibility: "draft",
      selectionState: "selected",
    });

    const absoluteDiskPath = path.join(tempDir, asset!.storagePath);
    expect(fs.existsSync(absoluteDiskPath)).toBe(true);
    expect(fs.readFileSync(absoluteDiskPath, "utf8")).toBe("image-binary");
  });

  it("creates an unattached draft asset when no post id is supplied", async () => {
    const blogRepo = new BlogPostDataMapper(db);
    const assetRepo = new BlogAssetDataMapper(db);
    const provider = {
      generate: vi.fn().mockResolvedValue({
        bytes: Buffer.from("unattached-image"),
        mimeType: "image/png",
        width: null,
        height: null,
        originalPrompt: "Loose prompt",
        finalPrompt: "Loose prompt",
        provider: "openai",
        model: "gpt-image-1",
      }),
    };
    const service = new BlogImageGenerationService(blogRepo, assetRepo, provider);

    const result = await service.generate({
      prompt: "Loose prompt",
      altText: "An unattached hero image.",
      size: "auto",
      quality: "auto",
      enhancePrompt: false,
      createdByUserId: "usr_admin",
    });

    const asset = await assetRepo.findById(result.assetId);

    expect(result).toMatchObject({
      postId: null,
      postSlug: null,
      title: null,
      visibility: "draft",
      width: null,
      height: null,
      finalPrompt: "Loose prompt",
    });
    expect(asset).toMatchObject({
      id: result.assetId,
      postId: null,
      visibility: "draft",
      altText: "An unattached hero image.",
    });
  });

  it("rejects generation requests for unknown posts", async () => {
    const service = new BlogImageGenerationService(
      new BlogPostDataMapper(db),
      new BlogAssetDataMapper(db),
      { generate: vi.fn() } as never,
    );

    await expect(service.generate({
      postId: "post_missing",
      prompt: "Prompt",
      altText: "Missing post image.",
      size: "1536x1024",
      quality: "high",
      enhancePrompt: true,
      createdByUserId: "usr_admin",
    })).rejects.toThrow(/post not found/i);
  });

  it("marks newly generated assets public when attached to an already published post", async () => {
    const blogRepo = new BlogPostDataMapper(db);
    const assetRepo = new BlogAssetDataMapper(db);
    const post = await blogRepo.create({
      slug: "published-hero-post",
      title: "Published Hero Post",
      description: "Published hero test.",
      content: "## Published\n\nBody.",
      createdByUserId: "usr_admin",
    });
    await blogRepo.publishById(post.id, "usr_admin");
    const service = new BlogImageGenerationService(blogRepo, assetRepo, {
      generate: vi.fn().mockResolvedValue({
        bytes: Buffer.from("published-image"),
        mimeType: "image/png",
        width: 1024,
        height: 1024,
        originalPrompt: "Prompt",
        finalPrompt: "Prompt",
        provider: "openai",
        model: "gpt-image-1",
      }),
    });

    const result = await service.generate({
      postId: post.id,
      prompt: "Prompt",
      altText: "Published hero image.",
      size: "1024x1024",
      quality: "medium",
      enhancePrompt: false,
      createdByUserId: "usr_admin",
    });

    expect(result.visibility).toBe("published");
    expect((await assetRepo.findById(result.assetId))?.visibility).toBe("published");
  });

  it("creates a private candidate instead of replacing the canonical hero image when setAsHero=false", async () => {
    const blogRepo = new BlogPostDataMapper(db);
    const assetRepo = new BlogAssetDataMapper(db);
    const post = await blogRepo.create({
      slug: "hero-candidate-post",
      title: "Hero Candidate Post",
      description: "Candidate generation test.",
      content: "## Candidate\n\nBody.",
      createdByUserId: "usr_admin",
    });
    const currentHero = await assetRepo.create({
      postId: post.id,
      kind: "hero",
      storagePath: "2026/hero-candidate-post/current.png",
      mimeType: "image/png",
      altText: "Current hero image.",
      visibility: "draft",
      selectionState: "selected",
      createdByUserId: "usr_admin",
    });
    await blogRepo.setHeroImageAsset(post.id, currentHero.id);

    const service = new BlogImageGenerationService(blogRepo, assetRepo, {
      generate: vi.fn().mockResolvedValue({
        bytes: Buffer.from("candidate-image"),
        mimeType: "image/png",
        width: 1536,
        height: 1024,
        originalPrompt: "Candidate prompt",
        finalPrompt: "Candidate prompt",
        provider: "openai",
        model: "gpt-image-1",
      }),
    });

    const result = await service.generate({
      postId: post.id,
      prompt: "Candidate prompt",
      altText: "Candidate hero image.",
      size: "1536x1024",
      quality: "high",
      enhancePrompt: false,
      setAsHero: false,
      createdByUserId: "usr_admin",
    });

    expect(result.selectionState).toBe("candidate");
    expect((await blogRepo.findById(post.id))?.heroImageAssetId).toBe(currentHero.id);
    expect((await assetRepo.findById(result.assetId))?.visibility).toBe("draft");
    expect((await assetRepo.findById(result.assetId))?.selectionState).toBe("candidate");
  });

  it("switches the canonical hero image and keeps non-selected published candidates private", async () => {
    const blogRepo = new BlogPostDataMapper(db);
    const assetRepo = new BlogAssetDataMapper(db);
    const post = await blogRepo.create({
      slug: "hero-switch-post",
      title: "Hero Switch Post",
      description: "Hero switching test.",
      content: "## Switch\n\nBody.",
      createdByUserId: "usr_admin",
    });
    await blogRepo.publishById(post.id, "usr_admin");

    const current = await assetRepo.create({
      postId: post.id,
      kind: "hero",
      storagePath: "2026/hero-switch-post/current.png",
      mimeType: "image/png",
      altText: "Current hero image.",
      visibility: "published",
      selectionState: "selected",
      createdByUserId: "usr_admin",
    });
    const candidate = await assetRepo.create({
      postId: post.id,
      kind: "hero",
      storagePath: "2026/hero-switch-post/candidate.png",
      mimeType: "image/png",
      altText: "Candidate hero image.",
      visibility: "draft",
      selectionState: "candidate",
      createdByUserId: "usr_admin",
    });
    await blogRepo.setHeroImageAsset(post.id, current.id);

    const service = new BlogImageGenerationService(blogRepo, assetRepo, { generate: vi.fn() } as never);

    await service.selectHeroImage(post.id, candidate.id, "usr_admin");

    expect((await blogRepo.findById(post.id))?.heroImageAssetId).toBe(candidate.id);
    expect((await assetRepo.findById(candidate.id))?.visibility).toBe("published");
    expect((await assetRepo.findById(candidate.id))?.selectionState).toBe("selected");
    expect((await assetRepo.findById(current.id))?.visibility).toBe("draft");
    expect((await assetRepo.findById(current.id))?.selectionState).toBe("candidate");
  });
});